"""
Contains methods to access payment methods given a payment id
"""

# List containing all payment methods
payment_methods = [
    'Instrument not defined',
    'Automated clearing house credit',
    'Automated clearing house debit',
    'ACH demand debit reversal',
    'ACH demand credit reversal',
    'ACH demand credit reversal',
    'ACH demand debit',
    'Hold',
    'National or regional clearing',
    'In cash',
    'ACH savings credit reversal',
    'ACH savings debit reversal',
    'ACH savings debit reversal',
    'ACH savings debit',
    'Bookentry credit',
    'Bookentry debit',
    'ACH demand cash concentration/disbursement (CCD) credit',
    'ACH demand cash concentration/disbursement (CCD) credit',
    'ACH demand corporate trade payment (CTP) credit',
    'Cheque',
    'Banker\'s draft',
    'Certified banker\'s draft',
    'Bank cheque (issued by a banking or similar establishment)',
    'Bill of exchange awaiting acceptance',
    'Certified cheque',
    'Local cheque',
    'ACH demand corporate trade payment (CTP) debit',
    'ACH demand corporate trade exchange (CTX) credit',
    'ACH demand corporate trade exchange (CTX) debit',
    'Credit transfer',
    'Debit transfer',
    'ACH demand cash concentration/disbursement plus (CCD+) credit',
    'ACH demand cash concentration/disbursement plus (CCD+) debit',
    'ACH prearranged payment and deposit (PPD)',
    'ACH savings cash concentration/disbursement (CCD) credit',
    'ACH savings cash concentration/disbursement (CCD) debit',
    'ACH savings corporate trade payment (CTP) credit',
    'ACH savings corporate trade payment (CTP) debit',
    'ACH savings corporate trade exchange (CTX) credit',
    'ACH savings corporate trade exchange (CTX) debit',
    'ACH savings cash concentration/disbursement plus (CCD+) credit',
    'Payment to bank account',
    'ACH savings cash concentration/disbursement plus (CCD+) debit',
    'Accepted bill of exchange',
    'Referenced home-banking credit transfer',
    'Interbank debit transfer',
    'Home-banking debit transfer',
    'Bank card',
    'Direct debit',
    'Payment by postgiro',
    'FR, norme 6 97-Telereglement CFONB (French Organisation for',
    'Urgent commercial payment',
    'Urgent Treasury Payment',
    'Credit card',
    'Debit card',
    'Bankgiro',
    'Standing agreement',
    'SEPA credit transfer',
    'SEPA direct debit',
    'Promissory note',
    'Promissory note signed by the debtor',
    'Promissory note signed by the debtor and endorsed by a bank',
    'Promissory note signed by the debtor and endorsed by a third party',
    'Promissory note signed by a bank',
    'Promissory note signed by a bank and endorsed by another bank',
    'Promissory note signed by a third party',
    'Promissory note signed by a third party and endorsed by a bank',
    'Online payment service',
    'Bill drawn by the creditor on the debtor',
    'Bill drawn by the creditor on a bank',
    'Bill drawn by the creditor, endorsed by another bank',
    'Bill drawn by the creditor on a bank and endorsed by a third party',
    'Bill drawn by the creditor on a third party',
    'Bill drawn by creditor on third party, accepted and endorsed by bank',
    'Not transferable banker\'s draft',
    'Not transferable local cheque',
    'Reference giro',
    'Urgent giro',
    'Free format giro',
    'Requested method for payment was not used',
    'Clearing between partners'
]
def get_payment_method(self, payment_id: int)->str:
    return self.payment_methods[payment_id - 1]
